version: '3'

networks:
    laravel:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx-web
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./src:/var/www/app-web
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-web
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app-web
        volumes:
            - ./src:/var/www/app-web
        ports:
            - "9000:9000"
        networks:
            - laravel